//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treningelo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TpAllomas
    {
        public int Id { get; set; }
        public string Nev { get; set; }
        public string Anyag { get; set; }
        public decimal Pontertek { get; set; }
        public int TeruletId { get; set; }
        public Nullable<int> SorId { get; set; }
    }
}
