//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treningelo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TpTrening
    {
        public int ID { get; set; }
        public string DolgozoTsz { get; set; }
        public bool Oktathat { get; set; }
        public System.DateTime TreningStart { get; set; }
        public Nullable<System.DateTime> TreningEnd { get; set; }
        public int TeruletId { get; set; }
        public int AllomasId { get; set; }
        public int SorId { get; set; }
        public string Megjegyzes { get; set; }
        public bool Mentoral { get; set; }
        public string Mentor { get; set; }
    }
}
